### ISSUE TITLE
[Feature Request] Add highlight groups for additional plugins

### ISSUE THREAD

**Issue by Zane-** [Iron-E/nvim-highlite#25]
Hello,

Interesting plugin you have here. I would love to use it, but it is missing support for a few plugins I set highlights for in my config.

These are namely:

* [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim)
* [sniprun](https://github.com/michaelb/sniprun)
* [leap.nvim](https://github.com/ggandor/leap.nvim)
* [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui)
* [nvim-dap](https://github.com/mfussenegger/nvim-dap)
* [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)

Would it be possible to add support for their highlight groups?

Thanks!

**Comment by Iron-E** [comment]
Thanks for taking an interest in this plugin!

I'd love to add more support for plugins. Those all look doable, except for `nvim-dap` which I was never able to get working correctly. If you feel like [contributing](https://github.com/Iron-E/nvim-highlite/blob/master-v4/doc/contributing.md) the groups for `nvim-dap`/`-ui`, I'd be happy to help answer any questions you have.

Keep in mind, [custom highlights are compatible](https://github.com/Iron-E/nvim-highlite#how-can-i-override-highlights-in-my-initlua) with this plugin. So if you have `nvim-dap` highlights you like, you can keep using them (or [add them to a custom colorscheme](https://github.com/Iron-E/nvim-highlite/blob/master-v4/doc/advanced-usage.md#2a-overriding-groups-optional)).

I'll get to work on the others when I get my next chance :)

**Comment by Iron-E** [comment]
Turns out neo-tree works out of the box here. Still working on the others. I'll keep this list updated until the issue closes

* [x] [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim)
* [x] [sniprun](https://github.com/michaelb/sniprun)
* [x] [leap.nvim](https://github.com/ggandor/leap.nvim)
* [ ] [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui)
* [ ] [nvim-dap](https://github.com/mfussenegger/nvim-dap)
* [x] [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)

**Comment by Iron-E** [comment]
@Zane- I added support for all of the plugins you mentioned but `nvim-dap`. I'm going to open a separate issue for that.

I forgot to mention [earlier](https://github.com/Iron-E/nvim-highlite/issues/25#issuecomment-1527676820) that `highlite.export` isn't held back by support for plugins, since it uses another colorscheme as a base. Whatever that colorscheme defines will be preserved.

Feel free to open further issues or [discussions](https://github.com/Iron-E/nvim-highlite/discussions) as necessary, I'll be happy to help.
